DefaultContentLanguage = "en"
baseURL = ""
languageCode = "en-us"
summaryLength = 10
title = "BantamTechnologies"
[[menu.nav]]
URL = "services"
name = "Services"
weight = 3
[[menu.nav]]
URL = "contact-us"
name = "Contact"
weight = 8
[[menu.nav]]
URL = "career"
name = "Careers"
weight = 10
[params]
author = "Bantam Technologies"
custom_css = ["css/custom.css"]
description = "BantamTechnologies provides cyber security services and applications to meet business writ large. The unconventional approach in the security field and a solution to SMBs. A solution for everyone."
gmapAPI = ""
googleAnalitycsID = ""
home = "Home"
logo = "images/logo.png"
[params.banner]
bgImage = "images/backgrounds/bantam-blue-straight.jpeg"
btn = true
btnText = "Our Services"
btnURL = "#services"
content = "Simplify Security"
enable = true
heading = "Bantam Technologies"
icon = "tf-ion-play"
[params.counter]
bgImage = "images/backgrounds/bg-1.jpg"
enable = false
[[params.counter.counterItem]]
count = 320
icon = "tf-ion-android-happy"
title = "Happy Clients"
[[params.counter.counterItem]]
count = 565
icon = "tf-ion-archive"
title = "Projects completed"
[[params.counter.counterItem]]
count = 95
icon = "tf-ion-thumbsup"
title = "Positive feedback"
[[params.counter.counterItem]]
count = 2500
icon = "tf-ion-coffee"
title = "Cups of Coffee"
[params.cta]
btnText = "Start a project with us"
btnURL = "#"
content = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis tenetur odio impedit incidunt? Omnis accusantium ea reiciendis, fugit commodi nostrum."
enable = false
title = "Great Design & Incredible Features"
[taxonomies]
author = "author"
category = "categories"
tag = "tags"
