---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
- type: document
  path: data/about2.yml
  label: About Section
- type: directory
  path: data/offices
  label: Office Locations
  create: all
  match: "**"
  new_doc_ext: yml
  templates:
  - office-location
- type: document
  path: data/service.yml
  label: Service Section
- type: document
  path: data/consulting.yml
  label: Consulting Section
- type: document
  path: data/contact.yml
  label: Contact Section
- type: document
  path: data/career.yml
  label: Work Here
- type: document
  path: data/footer.yml
  label: Footer Config
- type: document
  path: config.toml
  label: CONFIG.TOML
- type: directory
  path: layouts
  label: Pages
  create: all
  match: "**/*"
upload_dir: static/images
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.55.2
  - RUBY_VERSION=2.6.1
  preview_output_directory: public
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.55.0
