---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
- type: document
  path: data/service.yml
  label: Service Section
  match: "**/*"
- type: document
  path: data/consulting.yml
  label: Consulting Section
  match: "**/*"
- type: document
  path: data/contact.yml
  label: Contact Section
  match: "**/*"
- type: document
  path: data/career.yml
  label: Work Here
  match: "**/*"
- type: document
  path: data/footer.yml
  label: Footer Config
- type: document
  path: config.toml
  label: CONFIG.TOML
- type: directory
  path: layouts
  label: Pages
  create: all
  match: "**/*"
upload_dir: static/images
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.55.0
  - RUBY_VERSION=2.6.1
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.55.0
  preview_output_directory: public
  output_directory: public
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.55.0
